baseURL = 'https://www.qsjob.fun'  # 换成你的真实域名
locale = 'zh-cn'
title = '码一行'
theme = 'PaperMod'
defaultContentLanguage = "zh"

# 开启搜索功能必须配置
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[imaging]
  quality = 75
  resampleFilter = "lanczos"

[params]
  defaultTheme = "auto"
  ShowShareButtons = true  # 开启分享功能【文章页】
  # ShowReadingTime = true
  # 显示文章目录 (TOC)
  ShowToc = false
  TocOpen = false
  figurePositionShow = true
  ShowCodeCopyButtons = true  # 开启代码块复制按钮
  ShowPostNavLinks = true  # 开启上、下一页【文章页】

[params.homeInfoParams]
  Title = "你好！ 👋"
  Content = "欢迎来到我的博客"

[params.footer]
  # 自定义页脚
  text = "用 ❤️ 记录技术成长"

# [[menu.main]] 定义了主菜单的一个项目
[[menu.main]]
  name = "首页"           # 显示在菜单栏上的文字
  url = "/"              # 点击后跳转的链接路径
  weight = 1             # 权重，数字越小越靠左排列

[[menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 2

[[menu.main]]
  name = "搜索"
  url = "/search/"
  weight = 3